export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SET_USER = 'SET_USER';
export const CHANGE_PROFILE_SUCCESS = 'CHANGE_PROFILE_SUCCESS';

export const GET_USER_BOOKS_PENDING = 'GET_USER_BOOKS_PENDING';
export const GET_USER_BOOKS_SUCCESS = 'GET_USER_BOOKS_SUCCESS';
export const GET_USER_BOOKS_FAIL = 'GET_USER_BOOKS_FAIL';

export const ADD_BOOK_PENDING = 'ADD_BOOK_PENDING';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';

export const DELETE_BOOK_PENDING = 'DELETE_BOOK_PENDING';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';

export const GET_ALL_BOOKS_PENDING = 'GET_ALL_BOOKS_PENDING';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAIL = 'GET_ALL_BOOKS_FAIL';
