export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';

export const CHANGE_PROFILE_DATA_PENDING = 'CHANGE_PROFILE_DATA_PENDING';
export const CHANGE_PROFILE_DATA_SUCCESS = 'CHANGE_PROFILE_DATA_SUCCESS';
export const CHANGE_PROFILE_DATA_FAIL = 'CHANGE_PROFILE_DATA_FAIL';

export const GET_PROFILE_DATA_PENDING = 'GET_PROFILE_DATA_PENDING';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAIL = 'GET_PROFILE_DATA_FAIL';

export const GET_USER_BOOKS_PENDING = 'GET_USER_BOOKS_PENDING';
export const GET_USER_BOOKS_SUCCESS = 'GET_USER_BOOKS_SUCCESS';
export const GET_USER_BOOKS_FAIL = 'GET_USER_BOOKS_FAIL';

export const ADD_BOOK_PENDING = 'ADD_BOOK_PENDING';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';

export const DELETE_BOOK_PENDING = 'DELETE_BOOK_PENDING';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';

export const GET_ALL_BOOKS_PENDING = 'GET_ALL_BOOKS_PENDING';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAIL = 'GET_ALL_BOOKS_FAIL';

export const SET_USERID_SUCCESS = 'SET_USERID_SUCCESS';
export const SET_USERID_FAIL = 'SET_USERID_FAIL';
